### ISSUE TITLE
Devices not showing up

### ISSUE THREAD

**Issue by AryaJohary** [Coutj/Bluetooth_project#6]
I am currently using Ubuntu 20.04 LTS and just installed this setup. I followed properly and was able to start the executable fie. But, my headphones are not showing up by pressing Load button. I tried restarting Bluetooth, reconnecting to Headphones, used another Headphones, changed the configuration of Headphones from A2DP sink, to Headset Unit in Sound setting menu, but nothing worked. Kindly help me regarding it. 
Thank you very much

**Comment by Coutj** [comment]
I couldn't reproduce this problem, could you please try to run it on terminal using python3 main.py and share the output?
